
ALTER TABLE public.inventory_items
ADD COLUMN IF NOT EXISTS sku text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS supplier text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unit text DEFAULT 'pcs',
ADD COLUMN IF NOT EXISTS description text DEFAULT NULL;
